In [2]:
import numpy as np

In [3]:
#Diziyi np.array'e çevirmek
dizi = list[1,2,3,4]
dizi = np.array(dizi)

#MATRIS oluşturmak
dizi = np.array([[0,1,2],[3,4,5]])
dizi

#MATRIS TRANSPOZU
dizi.T # -> .T ile alınır

array([[0, 3],
       [1, 4],
       [2, 5]])

In [4]:
#0 - 1 ARASI RASTGELE MATRIS OLUŞTURMAK
dizi = np.random.rand(2,3) #2'e 3'lük 0-1 arası değerlerle rastgele matris

#RASTGELE INTEGER'LAR ILE ARRAY OLUŞTURMAK
dizi = np.random.randint(1,100,5) #1'le yüz arasında 5 tane tam sayı

#RASTGELE FLOAT'LAR ILE ARRAY OLUŞTURMAK
dizi = np.random.uniform(1,100,5) #1'le yüz arasında 5 tane kesirli sayı

#RASTGELE INTEGER'LAR ILE MATRIS OLUŞTURMAK
dizi = np.random.randint(1,100, size=(3,3)) # 1 - 100 arası 3'e 3 matris

#RASTGELE FLOAT'LAR ILE MATRIS OLUŞTURMAK
dizi = np.random.uniform(1,100, size=(3,3)) # 1 - 100 arası 3'e 3 kesirli sayı matris


In [5]:
#Sıfır Dizisi
sifirlar = np.zeros((2,3))
sifirlar

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
#Bir Dizisi
birler = np.ones((4,4))
birler

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
#np.arange(start, stop, step) – Belirli aralıkla sayılar
dizi = np.arange(0,10,2) # 0'dan 10'a kadar 2'şer artan
dizi

array([0, 2, 4, 6, 8])

In [8]:
#np.linspace(start, stop, n) – Belirli aralıkta eşit bölünmüş n sayı
dizi = np.linspace(0,1,5) #Sıfırla bir arasını 5'e böl
dizi

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
dizi = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]]) #3 boyutlu matris
dizi.shape # -> Dizinin şeklini yazdırır
dizi.ndim # -> Dizinin kaç boyutlu olduğunu gösterir
dizi.dtype # -> Dizi elemanlarının türünü gösterir
dizi = np.array([[1,2,3], [4,5,6]], dtype='float32') # -> Şeklinde önceden type belirlenebilir

In [10]:
###INDEKSLEME VE SLICING - SATIR VE SUTUN ERİŞİMİ###
#Tek boyutlu arraylerde

tekBoyut = np.array([1,2,3,4,5,6])
tekBoyut[0]
tekBoyut[-1]
tekBoyut[1]
tekBoyut[::2]
tekBoyut[1:4:2]

#Iki boyutlu matrislerde

ikiBoyut = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
ikiBoyut[1][2] # -> 1.satır 2.sutun
ikiBoyut[1,2] # -> 1.satır 2.sütun alternatifi
ikiBoyut[0] # -> 0.satırın hepsi
ikiBoyut[:, 2] # -> Tüm satırlardan 2.sütun
ikiBoyut[2, :] # -> 2.satırın tüm sütunları
ikiBoyut[0:2, 1:3] # -> 0.satırdan 2.satıra kadar (2 dahil değil), 


array([[2, 3],
       [5, 6]])

In [11]:
ikiBoyut + 2 # -> Her elemana 4 işlem yapma. Sadece yazdırır arrayi DEĞİŞTİRMEZ
ikiBoyut ** 2 # -> Her elemanın üssünü alma. Sadece yazdırır arrayi DEĞİŞTİRMEZ

np.sum(ikiBoyut) # -> Elemenlar toplamı
np.std(ikiBoyut) # -> Standart sapma
np.mean(ikiBoyut) # -> Ortalaması
np.max(ikiBoyut)
np.min(ikiBoyut)
np.median(ikiBoyut)

np.float64(6.5)

In [12]:
### MATRIS ÇARPIMI ###
## MATRIS ÇARPINDA EŞLEŞME ilk matris (m,n) ise ikinci matris (n,p) şeklinde olmalı. 1.'nin sütunu ile 2.'nin satır sayısı aynı olmalı

ikinciIkiBoyut = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
ikiBoyut = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
np.dot(ikinciIkiBoyut, ikiBoyut)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200],
       [173, 206, 239, 272]])

In [13]:
dz1 = np.array([[1,2],[4,5]]) # -> (2,2) matris çarpımı örneği
dz2 = np.array([[1,2],[4,5]])
np.dot(dz1, dz2)

array([[ 9, 12],
       [24, 33]])

In [14]:
### Broadcasting
# Farklı boyutlardaki diziler üzerinde işlem yapar
array1 = np.array([1,2,3])
array2 = np.array([[1,2,3], [4,5,6]])

array1 + array2  # -> Array2'nin her boyutundaki dizileri Array1 dizisi ile toplar

array([[2, 4, 6],
       [5, 7, 9]])

In [15]:
### Dizi Birleştirme ve Bölme

# Birleştirme (Concatenate)
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

np.hstack((a,b)) # -> Çıktısı tek bir array. Genellikle 1D veya 2D'de kullanılır. Kullanımı daha basittir. Çıktısı [1, 2, 3, 4, 5, 6, 7, 8]
np.concatenate((a,b), axis=1) # -> Aynı şekilde birleştirir. Fakat axis parametresi alabilir. Bu sayede dikey veya yatay birleştirme yapılabilir

# Bölme (Split)
splitArray = np.array([1,2,3,4,5,6,7,8,9])
np.split(splitArray, 3) # -> Diziyi n parçaya böler. Bu örnekte 3 parça


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [ ]:
### FONKSIYONEL PROGRAMLAMA ###      ### EN ÖNEMLİLERDEN ###
# Dizinin her elemanına belirlenen fonksiyonu uygular #

def cube(x):
    return x ** 3

arr = np.array([1,2,3,4])

cubedArr = np.vectorize(cube)
cubedArr(arr)


array([ 1,  8, 27, 64])

In [ ]:
### LOGICAL OPERATIONS ###
# True False dizisi döndürür. Her eleman için karşılaştırma yapar #
# Diziler AYNI BOYUTLARDA ve AYNI ELEMAN SAYILARINA sahip olmalıdır #

a = np.array([1, 5, 11, 9])
b = np.array([2, 3, 8, 9])

a > b

array([False,  True,  True, False])